### ISSUE TITLE
Uopštenje projekta

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-004-rebubbled#1]
Da li možete da napravite program tako da nemate specijalne slučajeve da li postoji jedna ili dve loptice? Ovo bi pojednostavilo dobar deo koda, i omogućilo dodavanje i više loptica od dve da budu prikazane odjednom.

**Comment by soleova** [comment]
Pokusacu da popravim sve sto se da popraviti. Takodje, pokusala sam da izmenim bounce funkciju tako da mi prima koordinate loptica u zavisnosti od toga za koju lopticu pozovem funkciju, medjutim tako nije htelo da mi lepo uvecava koordinate. To bi svakako resilo problem ponavljanja istih funkcija, pokusacu to da izmenim da lepo radi.

**Comment by soleova** [comment]
Dodato prikazivanje vise loptica odjednom.
